# Generated by Django 5.1.2 on 2024-12-11 16:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_id",
                    models.CharField(
                        default=core.models.generate_complaint_id,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("phone", models.CharField(max_length=15, verbose_name="Phone Number")),
                ("taluk", models.CharField(max_length=100, verbose_name="Taluk")),
                ("district", models.CharField(max_length=100, verbose_name="District")),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("transport", "Transport"),
                            ("agriculture", "Agriculture"),
                            ("water", "Water"),
                            ("education", "Education"),
                            ("electricity", "Electricity"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Department",
                    ),
                ),
                ("address", models.TextField(verbose_name="Address")),
                ("complaint", models.TextField(verbose_name="Complaint Description")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
            ],
        ),
    ]
