# Generated by Django 5.1.2 on 2024-12-13 04:57

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_complaint"),
    ]

    operations = [
       
        
  

migrations.AddField(
    model_name="complaint",
    name="created_at",
    field=models.DateTimeField(auto_now_add=True, default=timezone.now),
    preserve_default=False,
),

        migrations.AddField(
            model_name="complaint",
            name="location",
            field=models.CharField(default="Default", max_length=255),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complaint",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complaint_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="department",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
