# Generated by Django 5.1.2 on 2024-12-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_complaint_district_remove_complaint_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="location",
            field=models.CharField(default="Default Location", max_length=255),
        ),
    ]
