# Generated by Django 5.1.4 on 2024-12-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_complaint_location'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('solved', 'Solved')], default='pending', max_length=20),
        ),
    ]
