# Generated by Django 5.1.4 on 2024-12-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_complaint_district_remove_complaint_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='district',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='state',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='taluk',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('solved', 'Solved')], default='pending', max_length=20),
        ),
    ]
