# Generated by Django 5.1.2 on 2024-12-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_complaint_district_remove_complaint_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="department",
            field=models.CharField(
                choices=[
                    ("health", "Health"),
                    ("transport", "Transport"),
                    ("agriculture", "Agriculture"),
                    ("water", "Water"),
                    ("education", "Education"),
                    ("electricity", "Electricity"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
