# Generated by Django 5.1.2 on 2024-12-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_complaint_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="department",
            field=models.CharField(max_length=50),
        ),
    ]
